bookmarks/bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
app_name = 'images'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace = 'social')),
    path('images/', include(('images.urls','images'), namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.urls import path
from . import views
app_name = 'images'
urlpatterns = [
    path('create/', views.image_create, name = 'create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/',views.image_like, name='like'),

]

bookmarks/images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    
    url = models.URLField()
    image = models.ImageField(upload_to='image/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)
    
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name = 'images_liked',
                                        blank = True)
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            super(Image, self).save(*args, **kwargs)
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("images:detail", args=[self.id, self.slug])
    

bookmarks/images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify
class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput,
        }
    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']
        extension = url.rsplit('.',1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL doesnot match the valid image requirements.')
        return url 
    def save(self, force_insert = False,
            force_update = False, commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title),
                                    image_url.rsplit('.',1)[1].lower())
        response = request.urlopen(image_url)
        image.save(image_name, ContentFile(response.read()), save=False)
        
        if commit:
            image.save()
        return image

bookmarks/images/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from .models import Image
from django.http import JsonResponse
from django.views.decorators.http import require_POST

@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit = False)
            
            new_item.user = request.user
            new_item.save()
            messages.success(request, 'Image added successfully')
            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm(data = request.GET)
    return render(request, 'images/image/create.html',
                  {'section': 'images', 'form':form})
    
def image_detail(request, id, slug):
    image = get_object_or_404(Image, id = id, slug = slug)
    return render(request, 'images/image/detail.html',{'section':'images','image':image})

@login_required
@require_POST
def image_like(request):
    image_id = require_POST.get('id')
    action = require_POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id= image_id)
            if action =='like':
                image.users_like.add(request.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status':'unliked'})
        except:
            pass
    return JsonResponse({'status':'ok'})

bookmarks/images/templates/images/image/create.html
{% extends 'base.html' %}

{% block title %}
    Bookmark an Image
{% endblock title %}
    

{% block content %}
    <h1>
        Bookmark an Image
    </h1>
    <img src = '{{request.GET.url}}' class='image-preview'>
    <form action='.' method ='post'>
        {{form.as_p}}
        {% csrf_token %}
        <input type = 'submit' value = 'Bookmark'>
    </form>
{% endblock content %}
    

bookmarks/images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}
    {{ image.title }}
{% endblock %}

{% block content %}
    <h1>{{ image.title }}</h1>
    <img src="{{ image.image.url }}" class="image-detail">

    {% with total_likes=image.users_like.count %}
        <div class="image-info">
            <div>
                <span class="count">
                    {{ total_likes }} like{{ total_likes|pluralize }}
                </span>
            </div>
            {{ image.description|linebreaks }}
        </div>
        <div class="image-likes">
            {% for user in image.users_like.all %}
                <div>
                    <img src="{{ user.profile.photo.url }}">
                    <p>{{ user.first_name }}</p>
                </div>
            {% empty %}
                Nobody likes this image yet.
            {% endfor %}
        </div>
    {% endwith %}
{% endblock %}

{% block domready %}
    <script>
        $(document).ready(function() {
            $('a.likebutton').click(function(e) {
                e.preventDefault();
                var action = $(this).data('action');
                var id = $(this).data('id');
                var url = '{% url "images:like" %}';
                $.ajax({
                    url: url,
                    method: 'POST',
                    data: {id: id, action: action},
                    success: function(data) {
                        if (data['status'] === 'ok') {
                            var previous_action = $('a.likebutton').data('action');
                            $('a.likebutton').data('action', previous_action === 'like' ? 'unlike' : 'like');
                            $('a.likebutton').text(previous_action === 'like' ? 'Unlike' : 'Like');
                            var previous_likes = parseInt($('span.count').text());
                            $('span.count').text(previous_action === 'like' ? previous_likes + 1 : previous_likes - 1);
                        }
                    }
                });
            });
        });
    </script>
{% endblock %}